In [1]:
import torch

In [2]:
a = torch.arange(1, 13, 1).reshape(3, 4).float()

In [3]:
a

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [4]:
a.requires_grad = True

In [5]:
a = torch.arange(1, 7, 1).reshape(2, 3).float()
a.requires_grad = True

In [21]:
a = torch.Tensor([[1, 2], [3, 4]]); a.requires_grad = True

b = a.mean(axis = 0)
c = b.sum()

c.backward()

print("output of mean: ", b)
print("gradient of a: ", a.grad)

output of mean:  tensor([2., 3.], grad_fn=<MeanBackward1>)
gradient of a:  tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])


In [6]:
import torch.nn as nn

In [7]:
pred = torch.arange(1, 7, 1).float(); pred.requires_grad = True
actual = torch.Tensor([1, 3, 2, 4, 5, 6])

loss = nn.MSELoss(reduction="sum")

output: torch.Tensor = loss(pred, actual)
output.backward()

print("Output of the loss function: ", output)
print(pred.grad)

Output of the loss function:  tensor(2., grad_fn=<MseLossBackward0>)
tensor([ 0., -2.,  2.,  0.,  0.,  0.])


In [8]:
d = a.half()
k = a.half()

e = d + k
f = e.sum()

a, d, k, e, f

(tensor([[1., 2., 3.],
         [4., 5., 6.]], requires_grad=True),
 tensor([[1., 2., 3.],
         [4., 5., 6.]], dtype=torch.float16, grad_fn=<ToCopyBackward0>),
 tensor([[1., 2., 3.],
         [4., 5., 6.]], dtype=torch.float16, grad_fn=<ToCopyBackward0>),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]], dtype=torch.float16, grad_fn=<AddBackward0>),
 tensor(42., dtype=torch.float16, grad_fn=<SumBackward0>))

In [9]:
f.backward()

In [10]:
a.grad

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [11]:
x = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)

y = x.sum()  # y is a vector: tensor([4., 6.], grad_fn=<SumBackward1>)

print(x, y)
y.retain_grad = True
y.backward()

tensor([[1., 2.],
        [3., 4.]], requires_grad=True) tensor(10., grad_fn=<SumBackward0>)


In [12]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [13]:
import numpy as np

In [14]:
a = np.arange(1, 13, 1).reshape(3, 4)

In [15]:
b = a + 1
b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [16]:
import torch.nn as nn

layer = nn.Linear(5, 10)

inp = torch.Tensor([1, 2, 3, 4, 5])

out = layer(inp)

print("Output from Linear layer: ", out)
print("Input shape: ", inp.shape)
print("Output shape: ", out.shape)

print(layer.weight.shape, layer.bias.shape)

Output from Linear layer:  tensor([-1.7602, -1.6158,  3.9906, -4.1399,  3.3804, -2.6154,  1.3862,  1.1908,
        -2.5090, -1.7173], grad_fn=<ViewBackward0>)
Input shape:  torch.Size([5])
Output shape:  torch.Size([10])
torch.Size([10, 5]) torch.Size([10])
