In [1]:
import torch

In [2]:
a = torch.arange(1, 13, 1).reshape(3, 4).float()

In [3]:
a

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [4]:
a.requires_grad = True

In [5]:
a = torch.arange(1, 7, 1).reshape(2, 3).float()
a.requires_grad = True

In [58]:
import numpy as np

In [62]:
a = np.array([[1, 2], [3, 4]])

std = np.std(a, keepdims=False)
print(std)

temp = (a - a.mean(keepdims=True)) ** 2

print(a.mean())
print(temp)

std = np.sqrt(temp.mean(keepdims=True))
std

1.118033988749895
2.5
[[2.25 0.25]
 [0.25 2.25]]


array([[1.11803399]])

In [81]:
a = torch.Tensor([[1, 2], [3, 4]])
a = a.to(torch.float32)
a.requires_grad = True

b = torch.var(a, axis=1)
c = b.sum()

c.backward()

print(b)
print(a.grad)

tensor([0.5000, 0.5000], grad_fn=<VarBackward0>)
tensor([[-1.,  1.],
        [-1.,  1.]])


In [7]:
import torch.nn as nn

In [8]:
pred = torch.arange(1, 7, 1).float(); pred.requires_grad = True
actual = torch.Tensor([1, 3, 2, 4, 5, 6])

loss = nn.MSELoss(reduction="sum")

output: torch.Tensor = loss(pred, actual)
output.backward()

print("Output of the loss function: ", output)
print(pred.grad)

Output of the loss function:  tensor(2., grad_fn=<MseLossBackward0>)
tensor([ 0., -2.,  2.,  0.,  0.,  0.])


In [9]:
d = a.half()
k = a.half()

e = d + k
f = e.sum()

a, d, k, e, f

(tensor([[1., 2.],
         [3., 4.]], requires_grad=True),
 tensor([[1., 2.],
         [3., 4.]], dtype=torch.float16, grad_fn=<ToCopyBackward0>),
 tensor([[1., 2.],
         [3., 4.]], dtype=torch.float16, grad_fn=<ToCopyBackward0>),
 tensor([[2., 4.],
         [6., 8.]], dtype=torch.float16, grad_fn=<AddBackward0>),
 tensor(20., dtype=torch.float16, grad_fn=<SumBackward0>))

In [10]:
f.backward()

In [11]:
a.grad

tensor([[2.5000, 2.5000],
        [2.5000, 2.5000]])

In [12]:
x = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)

y = x.sum()  # y is a vector: tensor([4., 6.], grad_fn=<SumBackward1>)

print(x, y)
y.retain_grad = True
y.backward()

tensor([[1., 2.],
        [3., 4.]], requires_grad=True) tensor(10., grad_fn=<SumBackward0>)


In [13]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [14]:
import numpy as np

In [15]:
a = np.arange(1, 13, 1).reshape(3, 4)

In [16]:
b = a + 1
b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [17]:
import torch.nn as nn

layer = nn.Linear(5, 10)

inp = torch.Tensor([1, 2, 3, 4, 5])

out = layer(inp)

print("Output from Linear layer: ", out)
print("Input shape: ", inp.shape)
print("Output shape: ", out.shape)

print(layer.weight.shape, layer.bias.shape)

Output from Linear layer:  tensor([ 2.1948,  0.2230,  1.8296,  1.1871,  1.2304,  1.1347, -1.8223,  2.1204,
        -0.1979, -3.8751], grad_fn=<ViewBackward0>)
Input shape:  torch.Size([5])
Output shape:  torch.Size([10])
torch.Size([10, 5]) torch.Size([10])


In [22]:
import torch

# Create a tensor with requires_grad=True
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)

# Split the tensor into two chunks
a, b = torch.split(x, 2)

# Perform some operations on the split tensors
y = (a * b).sum()

# Compute the gradients
y.backward()

# Print the gradients
print(x.grad)

tensor([3., 4., 1., 2.])


In [19]:
import numpy as np

# Create a random array 'x' with a random shape
x = np.arange(1, 13, 1).reshape((2, 3, 2))
print(x)

# Choose a random axis 'n' to split along
n = -1

# Choose a random number of splits 'k'
k = 2

# Split 'x' into 'k' parts along axis 'n'
parts = np.split(x, k, axis=n)

# Create index arrays for each part
indices = []
start = 0
for part in parts:
    idx = [slice(None)] * x.ndim
    idx[n] = slice(start, start + part.shape[n])
    indices.append(tuple(idx))
    start += part.shape[n]


from functools import partial

def back(index=0):
    part, idx = parts[index], indices[index]
    x[idx] += part


funcs = []
for i in range(len(parts)):
    f = partial(back, index = i)
    funcs.append(f)

print("--------")
print(funcs)

# Update the corresponding portions of 'x' with each part
for i, f in enumerate(funcs):
    f()
    print("after ", i+1)
    print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
--------
[functools.partial(<function back at 0x7fdb9869cdc0>, index=0), functools.partial(<function back at 0x7fdb9869cdc0>, index=1)]
after  1
[[[ 2  2]
  [ 6  4]
  [10  6]]

 [[14  8]
  [18 10]
  [22 12]]]
after  2
[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]]


In [1]:
import torch

In [3]:
q = torch.arange(1, 25, 1).reshape(2, 4, 3)
k = torch.arange(1, 25, 1).reshape(2, 4, 3)
v = torch.arange(1, 25, 1).reshape(2, 4, 3)

x = None
x = torch.cat([q, k], dim=-1)
x = torch.cat([x, v], dim=-1)

x.shape

torch.Size([2, 4, 9])

In [5]:
y = torch.cat([q, k, v], dim=-1)
y.shape

torch.Size([2, 4, 9])

In [7]:
l1 = [q]
l2 = [k, v]

final = l1 + l2
len(final)

3

In [33]:
import numpy as np

q = np.arange(1, 25, 1).reshape(2, 4, 3)
k = np.arange(1, 9, 1).reshape(2, 4, 1)
v = np.arange(1, 17, 1).reshape(2, 4, 2)

In [34]:
dim = -1

x = np.concatenate([q, k, v], axis=dim)
x.shape

(2, 4, 6)

In [35]:
l = [q, k, v]
sizes = [hi.shape[dim] for hi in l]

cum = np.cumsum(sizes[:-1])
cum

array([3, 4])

In [36]:
ys = np.split(x, cum, axis=dim)

print(np.array_equal(ys[0], q))
print(np.array_equal(ys[1], k))
print(np.array_equal(ys[2], v))

True
True
True


In [17]:
import mlx.core as mx
import numpy as np

a = [2, 3, 1]
b = mx.array(a)
c = np.array(a)

print(np.cumsum(b))

print(mx.cumsum(b).tolist())

[2 5 6]
[2, 5, 6]


In [7]:
all_false = mx.all(b)
all_false.item()

True

In [10]:
import numpy as np

c = np.array(a)
all_false = np.all(c)
all_false.item()

True

In [1]:
import numpy as np

In [8]:
a = np.arange(1, 25, 1).reshape(2, 2, 6)
heads = 3
b = np.reshape(a, (2, heads, 2, 6 // heads))

In [10]:
b.reshape(2, 2, 6).shape

(2, 2, 6)

In [5]:
import torch

a = torch.arange(1, 25, 1).reshape(2, 3, 4).float()
a.shape

torch.Size([2, 3, 4])

In [6]:
drop = torch.nn.Dropout()

In [7]:
b = drop(a)
b

tensor([[[ 0.,  4.,  6.,  0.],
         [ 0.,  0., 14., 16.],
         [ 0., 20.,  0.,  0.]],

        [[26., 28., 30.,  0.],
         [ 0., 36.,  0., 40.],
         [42.,  0., 46., 48.]]])

In [8]:
drop.eval()
c = drop(a)
c

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])

In [9]:
import mlx.core as mx

In [10]:
a = mx.array([[1, 6, 3], [5, 3, 2]], dtype=mx.float32)
mask = mx.array([[0, 1, 0], [1, 0, 0]], dtype=mx.int8)

a, mask

(array([[1, 6, 3],
        [5, 3, 2]], dtype=float32),
 array([[0, 1, 0],
        [1, 0, 0]], dtype=int8))

In [16]:
b = mx.where(mask, mx.array(-1), a)
b

array([[1, -1, 3],
       [-1, 3, 2]], dtype=float32)

In [13]:
import numpy as np

a = mx.array([[1, 6, 3], [5, 3, 2]], dtype=mx.float32)
mask = mx.array([[0, 1, 0], [1, 0, 0]], dtype=mx.int8)

a, mask

(array([[1, 6, 3],
        [5, 3, 2]], dtype=float32),
 array([[0, 1, 0],
        [1, 0, 0]], dtype=int8))

In [15]:
b = np.where(mask, np.array(-1), a)
b

array([[ 1., -1.,  3.],
       [-1.,  3.,  2.]], dtype=float32)