In [1]:
import torch

In [2]:
a = torch.arange(1, 13, 1).reshape(3, 4).float()

In [3]:
a

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [4]:
a.requires_grad = True

In [10]:
a = torch.arange(1, 7, 1).reshape(2, 3).float()
a.requires_grad = True

In [6]:
import torch.nn as nn

In [12]:
mod = nn.Sequential(
    nn.ReLU(),
    nn.Sigmoid()
)

out = mod(a)
l = out.sum()

l.backward()

print(a.grad)

tensor([[0.1966, 0.1050, 0.0452],
        [0.0177, 0.0066, 0.0025]])


In [8]:
d = a.half()
k = a.half()

e = d + k
f = e.sum()

a, d, k, e, f

(tensor(556., grad_fn=<SumBackward0>),
 tensor(556., dtype=torch.float16, grad_fn=<ToCopyBackward0>),
 tensor(556., dtype=torch.float16, grad_fn=<ToCopyBackward0>),
 tensor(1112., dtype=torch.float16, grad_fn=<AddBackward0>),
 tensor(1112., dtype=torch.float16, grad_fn=<SumBackward0>))

In [9]:
f.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [ ]:
a.grad

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [ ]:
x = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)

y = x.sum()  # y is a vector: tensor([4., 6.], grad_fn=<SumBackward1>)

print(x, y)
y.retain_grad = True
y.backward()

tensor([[1., 2.],
        [3., 4.]], requires_grad=True) tensor(10., grad_fn=<SumBackward0>)


In [ ]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1, 13, 1).reshape(3, 4)

In [ ]:
b = a + 1
b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
import torch.nn as nn

layer = nn.Linear(5, 10)

inp = torch.Tensor([1, 2, 3, 4, 5])

out = layer(inp)

print("Output from Linear layer: ", out)
print("Input shape: ", inp.shape)
print("Output shape: ", out.shape)

print(layer.weight.shape, layer.bias.shape)

Output from Linear layer:  tensor([ 0.6811, -2.2614, -2.1518, -1.4620,  1.5932, -0.5444, -0.4352,  2.9024,
        -0.1458,  0.6266], grad_fn=<ViewBackward0>)
Input shape:  torch.Size([5])
Output shape:  torch.Size([10])
torch.Size([10, 5]) torch.Size([10])
